export const CLIENT_PERMISSIONS = {
  COMPANY_READ: 'company.read',
  COMPANY_MANAGE: 'company.manage',
  ROLE_READ: 'role.read',
  ROLE_MANAGE: 'role.manage',
  KB_READ: 'kb.read',
  KB_MANAGE: 'kb.manage',
  KB_TEST: 'kb.test',
  SCRIPT_READ: 'script.read',
  SCRIPT_MANAGE: 'script.manage',
  PROMPT_READ: 'prompt.read',
  PROMPT_MANAGE: 'prompt.manage',
  SETTINGS_MANAGE: 'settings.manage',
  LEAD_READ_ALL: 'lead.read.all',
  LEAD_READ_ASSIGNED: 'lead.read.assigned',
  LEAD_REPLY: 'lead.reply',
  LEAD_ASSIGN: 'lead.assign',
  LEAD_STATUS: 'lead.status',
  LEAD_REVEAL_PII: 'lead.reveal_pii',
  LEAD_EXPORT: 'lead.export',
  CALL_INITIATE: 'call.initiate',
  CALL_READ: 'call.read',
  ANALYTICS_READ: 'analytics.read',
  ACTIVITY_READ: 'activity.read',
  CHANNEL_READ: 'channel.read',
  CHANNEL_MANAGE: 'channel.manage',
  CAMPAIGN_READ: 'campaign.read',
  CAMPAIGN_MANAGE: 'campaign.manage',
  CAMPAIGN_SEND: 'campaign.send',
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_READ_ALL: 'customer.read.all',
  CUSTOMER_MANAGE: 'customer.manage',
  FILE_READ: 'file.read',
  FILE_MANAGE: 'file.manage',
} as const;

export const CLIENT_PERMISSION_DESCRIPTIONS: Record<string, string> = {
  [CLIENT_PERMISSIONS.COMPANY_READ]: 'View companies',
  [CLIENT_PERMISSIONS.COMPANY_MANAGE]: 'Create / update / deactivate companies',
  [CLIENT_PERMISSIONS.ROLE_READ]: 'View role assignments',
  [CLIENT_PERMISSIONS.ROLE_MANAGE]: 'Grant / revoke roles',
  [CLIENT_PERMISSIONS.KB_READ]: 'List knowledge documents',
  [CLIENT_PERMISSIONS.KB_MANAGE]: 'Upload / delete knowledge documents, re-index',
  [CLIENT_PERMISSIONS.KB_TEST]: 'Run retrieval tests against the knowledge base',
  [CLIENT_PERMISSIONS.SCRIPT_READ]: 'View conversation scripts',
  [CLIENT_PERMISSIONS.SCRIPT_MANAGE]: 'Create / edit / activate scripts',
  [CLIENT_PERMISSIONS.PROMPT_READ]: 'View prompts',
  [CLIENT_PERMISSIONS.PROMPT_MANAGE]: 'Edit prompts',
  [CLIENT_PERMISSIONS.SETTINGS_MANAGE]: 'Edit company AI settings',
  [CLIENT_PERMISSIONS.LEAD_READ_ALL]: 'See every conversation in the company',
  [CLIENT_PERMISSIONS.LEAD_READ_ASSIGNED]: 'See only conversations assigned to me',
  [CLIENT_PERMISSIONS.LEAD_REPLY]: 'Send a message into a conversation',
  [CLIENT_PERMISSIONS.LEAD_ASSIGN]: 'Assign a conversation to a user',
  [CLIENT_PERMISSIONS.LEAD_STATUS]: 'Change conversation status',
  [CLIENT_PERMISSIONS.LEAD_REVEAL_PII]: "Reveal a customer's real contact details",
  [CLIENT_PERMISSIONS.LEAD_EXPORT]: 'Export leads',
  [CLIENT_PERMISSIONS.CALL_INITIATE]: 'Place an outbound call for a lead',
  [CLIENT_PERMISSIONS.CALL_READ]: 'View call history for a lead',
  [CLIENT_PERMISSIONS.ANALYTICS_READ]: 'View dashboards',
  [CLIENT_PERMISSIONS.ACTIVITY_READ]: 'Read the activity log',
  [CLIENT_PERMISSIONS.CHANNEL_READ]: 'View connected WhatsApp / Facebook / Instagram accounts',
  [CLIENT_PERMISSIONS.CHANNEL_MANAGE]: 'Connect, edit and disconnect social channels',
  [CLIENT_PERMISSIONS.CAMPAIGN_READ]: 'View campaigns and their results',
  [CLIENT_PERMISSIONS.CAMPAIGN_MANAGE]: 'Create and edit campaigns and contact lists',
  [CLIENT_PERMISSIONS.CAMPAIGN_SEND]: 'Start, pause, cancel and retry a campaign',
  [CLIENT_PERMISSIONS.CUSTOMER_READ]: 'View customers assigned to me',
  [CLIENT_PERMISSIONS.CUSTOMER_READ_ALL]: 'View every customer in the company',
  [CLIENT_PERMISSIONS.CUSTOMER_MANAGE]: 'Create, edit, convert and delete customers',
  [CLIENT_PERMISSIONS.FILE_READ]: 'List and download stored documents',
  [CLIENT_PERMISSIONS.FILE_MANAGE]: 'Upload and delete stored documents',
};
